
version: 1
formatters:
  # human:
  #   format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  json:
    (): app.logger.JSONFormatter
    fmt_keys: 
      # foo : bar
      - levelname
      - timestamp
      - name
      - module
      - funcName
      - lineno
      - threadName
handlers:
  stdout_dev:
    class: rich.logging.RichHandler
    level: DEBUG
  stdout_min:
    class: logging.StreamHandler
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    stream: ext://sys.stderr
loggers:
  root:
    level: DEBUG
    handlers:
      - stdout_dev
  uvicorn.error:
    level: INFO
  uvicorn:
    level: INFO

