# NOTE: The build should happen in the context of the root directory.
#       All paths should be written relative to the root in directives.
FROM acederberg/captura:0.1.3-alpha AS base

ENV CAPTURA_HOOKS="/home/captura/.captura/hooks.py" \
  CAPTURA_TEXT_STATUS="/home/captura/.captura/text.status.yaml" \
  CAPTURA_TEXT_CONFIG="/home/captura/.captura/text.yaml" 

COPY --chown=captura:captura ./docker/hooks.py /home/captura/.captura/hooks.py
COPY --chown=captura:captura ./docker/plugin.yaml .


FROM base AS development
COPY ./docker/bashrc /home/captura/.bashrc
ENTRYPOINT ["bash"]


FROM base AS production
COPY --chown=captura:captura . ./plugins/text
RUN bash /home/captura/docker.sh plugins >> /home/captura/.captura/logs/ci.log

